defaults: &defaults

  ### ArchivesSpace connection
  archivesspace_frontend_host: localhost
  archivesspace_solr_host: localhost
  archivesspace_backend_host: localhost
  archivesspace_https: '1'
  archivesspace_username: admin
  archivesspace_password: n0tadm1n
  archivesspace_solr_core_path: '/collection1/'

  ### email settings
  order_notification_default_email: 'trthorn2@ncsu.edu'
  order_notification_digital_items_email: 'trthorn2@ncsu.edu'
  circa_email: 'scrc@ncsu.edu'
  circa_email_display_name: 'NCSU Special Collections Research Center'

  ### Solr
  solr_host: localhost
  solr_port: '8983'
  solr_core_name: 'circa'
  solr_core_path: /solr/circa/

  ### Wolftech LDAP
  wolftech_username: lib.kbox.service
  wolftech_password: W0lfp@ck

  ### misc options
  # use_devise_passwords: '1'
  send_order_notifications: '1'

development:
  <<: *defaults

test:
  <<: *defaults
  solr_core_name: 'circa_test'
  solr_core_path: /solr/circa_test/

staging:
  <<: *defaults


production:
  <<: *defaults
